name: Crowdin Sync

on:
    push:
        branches: [main]
        paths:
            - "apps/desktop/src/locales/en/**.json"
    schedule:
        - cron: "0 5 * * 1"
    workflow_dispatch:

jobs:
    synchronize-with-crowdin:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write

        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Crowdin GitHub Action
              uses: crowdin/github-action@v2
              with:
                  upload_sources: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

                  upload_translations: false
                  download_translations: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
                  create_pull_request: true
                  pull_request_title: "chore(l10n): New translations from Crowdin"
                  pull_request_body: "New translations detected and downloaded from Crowdin."
                  pull_request_base_branch_name: "main"
                  localization_branch_name: "chore/crowdin-updates"

              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
                  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
